version: 2

sources:
  - name: staging
    database: cedar-unison-413811
     # For postgres:
      #database: production
    schema: ny_taxi_w4

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata

      - name: yellow_tripdata_beta